name: Update Date in README

# 触发条件
on:
  workflow_dispatch:
  # 定时触发
  schedule:
    # 每6小时获取一次
    - cron: '0 */12 * * *'

jobs:
  update-date:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Update date in README.md
        run: |
          # 获取当前日期，格式为 YYYY-MM-DD
          current_date=$(date +'%Y-%m-%d')

          # 检查 README.md 是否包含创建和修改日期
          if ! grep -q "## 更新时间" README.md; then
            echo "## 更新时间 $current_date" | cat - README.md > temp && mv temp README.md
          else
            # 将日期更新放到文件顶部
            sed -i "1s/^/## 更新时间 $current_date\n/" README.md
          fi


      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add README.md
          git commit -m "Update date in README.md to $current_date"
          git push
